spring:
  application:
    name: basic-wallet
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:eventstore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

axon:
  amqp:
    transaction-mode: transactional
    exchange: wallet.events

server:
  port: 8083